'use client'

import { useState } from 'react'
import jsPDF from 'jspdf'
import { detectGarmentType, detectRepairType, formatFullDate } from '@/lib/tokens'
import type { LogRow } from './RepairLogTable'

type ReportData = {
  brandName: string
  rows: LogRow[]
  thisMonth: number
  allTime: number
  avgTurnaround: number
  co2Kg: number
  garments: number
}

function triggerBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

function csvEscape(v: string | number): string {
  const s = String(v)
  if (s.includes(',') || s.includes('"') || s.includes('\n')) {
    return `"${s.replace(/"/g, '""')}"`
  }
  return s
}

function downloadCSV(data: ReportData) {
  const headers = ['Order ID', 'Date', 'Garment', 'Repair type', 'Status', 'Price (EUR)']
  const lines = [headers.join(',')]
  for (const r of data.rows) {
    lines.push(
      [
        `#FMF-${r.orderName.replace('#', '').slice(-4)}`,
        formatFullDate(r.createdAt),
        detectGarmentType(r.productTitle),
        detectRepairType(r.productTitle),
        r.status,
        parseFloat(r.price).toFixed(2),
      ]
        .map(csvEscape)
        .join(','),
    )
  }
  const blob = new Blob([lines.join('\n')], { type: 'text/csv;charset=utf-8' })
  const stamp = new Date().toISOString().slice(0, 10)
  triggerBlob(blob, `fmf-repairs-${data.brandName}-${stamp}.csv`)
}

function buildPDF(data: ReportData, title: string, subtitle: string): jsPDF {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()

  // Header
  doc.setFillColor(15, 110, 86)
  doc.rect(0, 0, pageWidth, 80, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(10)
  doc.text('REPAIRS BY FIXMYFASHION', 40, 32)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text(data.brandName, 40, 58)

  // Title
  doc.setTextColor(26, 26, 26)
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(16)
  doc.text(title, 40, 120)
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(107, 114, 128)
  doc.text(subtitle, 40, 140)

  // KPI summary
  const kpis = [
    ['Repairs this month', String(data.thisMonth)],
    ['All-time repairs', String(data.allTime)],
    ['Avg turnaround', data.avgTurnaround > 0 ? `${data.avgTurnaround} days` : '—'],
    ['Garments repaired', String(data.garments)],
    ['CO₂ saved', `${data.co2Kg.toLocaleString()} kg`],
  ]
  let y = 180
  doc.setTextColor(26, 26, 26)
  for (const [label, value] of kpis) {
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(10)
    doc.setTextColor(107, 114, 128)
    doc.text(label, 40, y)
    doc.setFont('helvetica', 'bold')
    doc.setFontSize(14)
    doc.setTextColor(26, 26, 26)
    doc.text(value, 220, y)
    y += 24
  }

  // Repair log table (top 30)
  y += 20
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(12)
  doc.text('Recent repairs', 40, y)
  y += 16
  doc.setFontSize(9)
  doc.setTextColor(107, 114, 128)
  const colX = [40, 110, 160, 290, 400, 490]
  ;['Order', 'Date', 'Garment / repair', 'Status', 'Price', ''].forEach((h, i) => doc.text(h, colX[i], y))
  y += 14
  doc.setTextColor(26, 26, 26)
  for (const r of data.rows.slice(0, 30)) {
    if (y > 780) {
      doc.addPage()
      y = 60
    }
    const garment = detectGarmentType(r.productTitle)
    const title = r.productTitle.length > 30 ? r.productTitle.slice(0, 30) + '…' : r.productTitle
    doc.text(`#FMF-${r.orderName.replace('#', '').slice(-4)}`, colX[0], y)
    doc.text(formatFullDate(r.createdAt), colX[1], y)
    doc.text(`${garment} · ${title}`, colX[2], y)
    doc.text(r.status, colX[3], y)
    doc.text(`€${parseFloat(r.price).toFixed(0)}`, colX[4], y)
    y += 14
  }

  // Footer
  const pageCount = doc.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(107, 114, 128)
    doc.text('Generated by FixMyFashion · dashboard.fixmyfashion.gr', 40, 820)
  }

  return doc
}

function downloadRangePDF(data: ReportData, from: string, to: string) {
  const start = from ? new Date(from) : new Date()
  const end = to ? new Date(to) : new Date()
  const label = `${start.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })} – ${end.toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}`

  const fromMs = start.getTime()
  const toMs = end.getTime() + 86_400_000 - 1
  const ranged = {
    ...data,
    rows: data.rows.filter((r) => {
      const t = new Date(r.createdAt).getTime()
      return t >= fromMs && t <= toMs
    }),
  }

  const doc = buildPDF(ranged, `Report — ${label}`, `Repair service performance for ${data.brandName}.`)
  doc.save(`fmf-report-${data.brandName}-${start.toISOString().slice(0, 10)}_${end.toISOString().slice(0, 10)}.pdf`)
}

function downloadSustainabilityCert(data: ReportData) {
  const now = new Date()
  const quarter = Math.floor(now.getMonth() / 3) + 1
  const label = `Q${quarter} ${now.getFullYear()}`
  const doc = buildPDF(data, `Sustainability certificate — ${label}`, `Verified environmental impact of the ${data.brandName} repair programme.`)
  doc.save(`fmf-sustainability-${data.brandName}-${label.replace(' ', '-')}.pdf`)
}

function isoDaysAgo(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  return d.toISOString().slice(0, 10)
}

export function ReportDownloads({ data }: { data: ReportData }) {
  const [delivery, setDelivery] = useState<'monthly_pdf_csv' | 'monthly_pdf' | 'off'>('monthly_pdf_csv')
  const [savedMsg, setSavedMsg] = useState('')

  // Default range = current calendar month
  const now = new Date()
  const defaultFrom = new Date(now.getFullYear(), now.getMonth(), 1).toISOString().slice(0, 10)
  const defaultTo = now.toISOString().slice(0, 10)
  const [from, setFrom] = useState(defaultFrom)
  const [to, setTo] = useState(defaultTo)

  function savePref() {
    // Supabase write deferred — just show optimistic confirmation for now
    setSavedMsg('Saved.')
    setTimeout(() => setSavedMsg(''), 2500)
  }

  const quarter = `Q${Math.floor(now.getMonth() / 3) + 1} ${now.getFullYear()}`

  return (
    <div className="space-y-6">
      <section className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white border border-black/10 rounded-xl p-5 flex flex-col md:col-span-1">
          <div className="text-xs uppercase tracking-wider text-gray-500">Monthly report</div>
          <div className="text-base font-semibold text-[#1a1a1a] mt-1">Date range PDF</div>
          <div className="mt-3 flex flex-col gap-2">
            <label className="text-xs text-gray-500 flex flex-col gap-1">
              <span>From</span>
              <input
                type="date"
                value={from}
                max={to}
                onChange={(e) => setFrom(e.target.value)}
                className="border border-black/10 rounded-lg px-2.5 py-1.5 text-sm bg-white"
              />
            </label>
            <label className="text-xs text-gray-500 flex flex-col gap-1">
              <span>To</span>
              <input
                type="date"
                value={to}
                min={from}
                onChange={(e) => setTo(e.target.value)}
                className="border border-black/10 rounded-lg px-2.5 py-1.5 text-sm bg-white"
              />
            </label>
            <div className="flex gap-1.5 flex-wrap mt-1">
              <QuickRange label="This month" from={defaultFrom} to={defaultTo} setFrom={setFrom} setTo={setTo} />
              <QuickRange label="Last 30d" from={isoDaysAgo(30)} to={defaultTo} setFrom={setFrom} setTo={setTo} />
              <QuickRange label="Last 90d" from={isoDaysAgo(90)} to={defaultTo} setFrom={setFrom} setTo={setTo} />
            </div>
          </div>
          <button
            onClick={() => downloadRangePDF(data, from, to)}
            className="mt-4 self-start px-3 py-1.5 rounded-lg border border-[#0F6E56] text-[#0F6E56] text-xs font-medium hover:bg-[#E1F5EE]"
          >
            Download PDF
          </button>
        </div>

        <DownloadCard title="Repair data" sub="CSV export" button="Download CSV" onClick={() => downloadCSV(data)} />
        <DownloadCard
          title="Sustainability certificate"
          sub={quarter}
          button="Download PDF"
          onClick={() => downloadSustainabilityCert(data)}
        />
      </section>

      <section className="bg-white border border-black/10 rounded-xl p-5">
        <h3 className="text-sm font-medium text-gray-700 mb-1">Scheduled delivery</h3>
        <p className="text-xs text-gray-500 mb-3">Automatically receive reports by email on the 1st of each month.</p>
        <div className="flex flex-wrap items-center gap-3">
          <select
            value={delivery}
            onChange={(e) => setDelivery(e.target.value as typeof delivery)}
            className="border border-black/10 rounded-lg px-3 py-2 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-[#0F6E56]/20"
          >
            <option value="monthly_pdf_csv">Monthly PDF + CSV</option>
            <option value="monthly_pdf">Monthly PDF only</option>
            <option value="off">Off</option>
          </select>
          <button
            onClick={savePref}
            className="px-4 py-2 rounded-lg bg-[#0F6E56] text-white text-sm font-medium hover:bg-[#0c5c48]"
          >
            Save
          </button>
          {savedMsg && <span className="text-xs text-[#0F6E56]">{savedMsg}</span>}
        </div>
      </section>
    </div>
  )
}

function QuickRange({
  label,
  from,
  to,
  setFrom,
  setTo,
}: {
  label: string
  from: string
  to: string
  setFrom: (v: string) => void
  setTo: (v: string) => void
}) {
  return (
    <button
      onClick={() => {
        setFrom(from)
        setTo(to)
      }}
      className="px-2 py-0.5 rounded text-[11px] text-gray-600 bg-gray-100 hover:bg-gray-200"
    >
      {label}
    </button>
  )
}

function DownloadCard({
  title,
  sub,
  button,
  onClick,
}: {
  title: string
  sub: string
  button: string
  onClick: () => void
}) {
  return (
    <div className="bg-white border border-black/10 rounded-xl p-5 flex flex-col">
      <div className="text-xs uppercase tracking-wider text-gray-500">{title}</div>
      <div className="text-base font-semibold text-[#1a1a1a] mt-1">{sub}</div>
      <button
        onClick={onClick}
        className="mt-4 self-start px-3 py-1.5 rounded-lg border border-[#0F6E56] text-[#0F6E56] text-xs font-medium hover:bg-[#E1F5EE]"
      >
        {button}
      </button>
    </div>
  )
}
